### ISSUE TITLE
[BUG] Wayland bug with Flatpak

### ISSUE THREAD

**Issue by imLinguin** [ferraridamiano/ConverterNOW#169]
**Describe the bug**
On Flatpak version on Wayland there are graphical glitches and the window decoration is missing (titlebar, close minimize etc...)

**To Reproduce**
1. Launch the app on Wayland

**Expected behavior**
No glitches, present window decoration.

**Screenshots / gif**
https://user-images.githubusercontent.com/62100117/177170318-34ae6680-0fee-410f-b9bd-db110055ee46.mp4

**Device**
- Device type: Linux
- OS version: Manjaro KDE 5.24.5 Wayland
- Device type:  ThinkPad T490 Intel UHD 620 16GB ram

**Additional context**

**Comment by ferraridamiano** [comment]
Hi, thank you for filing this issue. I can't replicate this bug on my setup (Kubuntu 22.04 with KDE 5.24.4). Could you please try to launch the app with the command `flatpak run io.github.ferraridamiano.ConverterNOW` and paste here the output? Thank you!

**Comment by imLinguin** [comment]
Log:
```
$ flatpak run io.github.ferraridamiano.ConverterNOW

(converternow:2): Gtk-WARNING **: 19:34:24.165: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:24.166: drawing failure for widget 'GtkBox': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:24.166: drawing failure for widget 'GtkHeaderBar': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:24.166: drawing failure for widget 'GtkApplicationWindow': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:24.228: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:24.228: drawing failure for widget 'GtkBox': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:24.228: drawing failure for widget 'GtkHeaderBar': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:24.228: drawing failure for widget 'GtkApplicationWindow': error occurred in libfreetype
flutter: Null check operator used on a null value
flutter: #0      getPropertyUiList (package:converterpro/utils/property_unit_list.dart:15)
flutter: #1      SplashScreen.build.<anonymous closure> (package:converterpro/pages/splash_screen.dart:24)
flutter: #2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
flutter: #3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1089)
flutter: #4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995)
flutter: #8      _invoke (dart:ui/hooks.dart:151)
flutter: #9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
flutter: #10     _drawFrame (dart:ui/hooks.dart:115)
flutter: (elided 3 frames from dart:async)

(converternow:2): Gtk-WARNING **: 19:34:26.111: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:26.112: drawing failure for widget 'GtkBox': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:26.112: drawing failure for widget 'GtkHeaderBar': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:26.112: drawing failure for widget 'GtkApplicationWindow': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:30.700: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:30.700: drawing failure for widget 'GtkBox': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:30.700: drawing failure for widget 'GtkHeaderBar': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:30.700: drawing failure for widget 'GtkApplicationWindow': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:32.033: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:32.033: drawing failure for widget 'GtkBox': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:32.033: drawing failure for widget 'GtkHeaderBar': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:32.033: drawing failure for widget 'GtkApplicationWindow': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:32.769: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:32.769: drawing failure for widget 'GtkBox': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:32.769: drawing failure for widget 'GtkHeaderBar': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:32.769: drawing failure for widget 'GtkApplicationWindow': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:33.608: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 19:34:33.608: drawing failure for widget 'GtkBox': error occurred in libfreetype
```

**Comment by ferraridamiano** [comment]
OK, let's try to get rid of some of the culprits. Could you try to download [converternow-linux.tar.gz](https://github.com/ferraridamiano/ConverterNOW/releases/tag/v3.1.2), extract it and execute it from the terminal. Then, tell me if the issue persists, and eventually past here the output of the terminal. Thank you!

**Comment by ferraridamiano** [comment]
Could you try deleting the Converter NOW folder that you can find in `~/.local/share/`? Then try again both the flatpak version and the app from the archive. Tell me if it works

**Comment by imLinguin** [comment]
Flatpak
```
$ flatpak run io.github.ferraridamiano.ConverterNOW

(converternow:2): Gtk-WARNING **: 14:13:22.329: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 14:13:22.330: drawing failure for widget 'GtkBox': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 14:13:22.330: drawing failure for widget 'GtkHeaderBar': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 14:13:22.330: drawing failure for widget 'GtkApplicationWindow': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 14:13:22.390: drawing failure for widget 'GtkLabel': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 14:13:22.390: drawing failure for widget 'GtkBox': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 14:13:22.390: drawing failure for widget 'GtkHeaderBar': error occurred in libfreetype

(converternow:2): Gtk-WARNING **: 14:13:22.390: drawing failure for widget 'GtkApplicationWindow': error occurred in libfreetype
flutter: Null check operator used on a null value
flutter: #0      getPropertyUiList (package:converterpro/utils/property_unit_list.dart:15)
flutter: #1      SplashScreen.build.<anonymous closure> (package:converterpro/pages/splash_screen.dart:24)
flutter: #2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
flutter: #3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1089)
flutter: #4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995)
flutter: #8      _invoke (dart:ui/hooks.dart:151)
flutter: #9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
flutter: #10     _drawFrame (dart:ui/hooks.dart:115)
flutter: (elided 3 frames from dart:async)
```
Archive
```
$ ./converternow 
flutter: Null check operator used on a null value
flutter: #0      getPropertyUiList (package:converterpro/utils/property_unit_list.dart:15)
flutter: #1      SplashScreen.build.<anonymous closure> (package:converterpro/pages/splash_screen.dart:24)
flutter: #2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
flutter: #3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1089)
flutter: #4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995)
flutter: #8      _invoke (dart:ui/hooks.dart:151)
flutter: #9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
flutter: #10     _drawFrame (dart:ui/hooks.dart:115)
flutter: (elided 3 frames from dart:async)
```

Now flatpak version hangs in the same spot as archive one, still without window decorations.

**Comment by ferraridamiano** [comment]
Does it work with X11?

Could you trying installing [this app](https://flathub.org/apps/details/com.github.KRTirtho.Spotube)? It is an app built with the same framework (flutter) as Converter NOW. I need to be sure that it is not a flutter issue.

**Comment by imLinguin** [comment]
ConverterNOW works with X11

Spotube works fine on both Wayland and X11

**Comment by ferraridamiano** [comment]
Could you try updating to the latest flatpak version?
Otherwise I have no idea

**Comment by imLinguin** [comment]
Same issue on latest

**Comment by ferraridamiano** [comment]
Is this problem still valid? If yes, do you experience the same issue with the appimage version?

**Comment by imLinguin** [comment]
Seems to be working now! Thanks
