### ISSUE TITLE
Bug in Volume and Mass Conversion

### ISSUE THREAD

**Issue by AbuBakar988** [ferraridamiano/ConverterNOW#204]
When volume and mass is clicked in drawer the app gives an error. **"Null check operator used on a null value."**

Here is the complete log

<details><summary>LOG</summary>

```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building ConversionPage(dirty, dependencies: [_InheritedProviderScope<Conversions?>, _LocalizationsScope-[GlobalKey#5555e]]):
Null check operator used on a null value

The relevant error-causing widget was: 
  ConversionPage ConversionPage:file:///C:/Users/Public/Documents/ConverterNOW-master/lib/main.dart:53:48
When the exception was thrown, this was the stack: 
#0      ConversionPage.build (package:converterpro/pages/conversion_page.dart:47:57)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:4949:49)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#4      StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#10     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#24     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#32     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#33     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#38     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#40     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#44     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#48     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#51     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#53     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#57     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#61     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#67     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#71     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#74     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#76     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#79     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#81     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#86     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#87     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153:12)
#88     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2246:59)
#89     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1035:15)
#90     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2246:14)
#91     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228:7)
#92     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:316:5)
#93     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1973:7)
#94     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:999:18)
#95     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:513:19)
#96     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#97     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#98     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#99     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#100    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#101    _invoke (dart:ui/hooks.dart:148:13)
#102    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#103    _drawFrame (dart:ui/hooks.dart:115:31)
```
</details>

![Capture](https://user-images.githubusercontent.com/123187910/213743319-e57c958c-4236-4a14-812d-5ec3fedbf585.PNG)

**Comment by ferraridamiano** [comment]
Mmmmm interesting! Could you please tell me:
- the version of the app
- android version
- if you compiled from source or it is the apk from a store
- if you changed the properties or unit order
- if you changed the language

Thank you!

**Comment by ferraridamiano** [comment]
Did you run `melos bootstrap` before running `flutter run`?
On which platform are you building the code (windows, linux, macos)?
Could you try to build the app for the web? e.g. `flutter run -d chrome`

**Comment by AbuBakar988** [comment]
yes i ran the melos command.
i am building code on windows.
yes i tried to run on browser too, but same error in web for volume and mass.

![Capture](https://user-images.githubusercontent.com/123187910/213874017-3887b7b4-cf25-4e70-9dc7-836aabf2d146.PNG)

```
======== Exception caught by widgets library =======================================================
The following TypeErrorImpl was thrown building ConversionPage(dirty, dependencies: [_InheritedProviderScope<Conversions?>, _LocalizationsScope-[GlobalKey#98a30]]):
Unexpected null value.

The relevant error-causing widget was: 
  ConversionPage ConversionPage:file:///C:/Users/Public/Documents/ConverterNOW-master/lib/main.dart:53:48
When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
packages/converterpro/pages/conversion_page.dart 47:57                                                                         build
packages/flutter/src/widgets/framework.dart 4949:22                                                                            build
packages/flutter/src/widgets/framework.dart 4878:15                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4956:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6307:14                                                                            update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4956:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6307:14                                                                            update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6307:14                                                                            update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 5050:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 5082:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 5050:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 5082:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6307:14                                                                            update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6307:14                                                                            update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 5228:5                                                                             update
packages/flutter/src/widgets/inherited_notifier.dart 107:11                                                                    update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6307:14                                                                            update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 5050:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 5082:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 5228:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 5228:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 5050:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 5082:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4956:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4956:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 6307:14                                                                            update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 5228:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 5228:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 5050:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 5082:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 5050:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 5082:5                                                                             update
packages/flutter/src/widgets/framework.dart 3570:14                                                                            updateChild
packages/flutter/src/widgets/framework.dart 4904:16                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 5050:11                                                                            performRebuild
packages/flutter/src/widgets/framework.dart 4604:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 2667:18                                                                            buildScope
packages/flutter/src/widgets/layout_builder.dart 153:5                                                                         [_layout]
packages/flutter/src/rendering/object.dart 2246:59                                                                             <fn>
packages/flutter/src/rendering/object.dart 1035:15                                                                             [_enableMutationsToDirtySubtrees]
packages/flutter/src/rendering/object.dart 2246:7                                                                              invokeLayoutCallback
packages/flutter/src/widgets/layout_builder.dart 228:7                                                                         rebuildIfNecessary
packages/flutter/src/widgets/layout_builder.dart 316:5                                                                         performLayout
packages/flutter/src/rendering/object.dart 1973:7                                                                              [_layoutWithoutResize]
packages/flutter/src/rendering/object.dart 999:17                                                                              flushLayout
packages/flutter/src/rendering/binding.dart 513:19                                                                             drawFrame
packages/flutter/src/widgets/binding.dart 884:13                                                                               drawFrame
packages/flutter/src/rendering/binding.dart 378:5                                                                              [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1175:15                                                                            [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1104:9                                                                             handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1015:5                                                                             [_handleDrawFrame]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 1168:13               invoke
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 219:5                 invokeOnDrawFrame
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/initialization.dart 195:45                     <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
====================================================================================================
```

also when i try to add another conversion to the drawer it gives an error even i change the const maxConversionUnits to 20 or more. `const maxConversionUnits = 20;`

```
======== Exception caught by widgets library =======================================================
The following RangeError was thrown building CustomDrawer(dirty, dependencies: [GoRouterStateRegistryScope, _InheritedProviderScope<AppModel?>, _InheritedTheme, _LocalizationsScope-[GlobalKey#2c858], _ModalScopeStatus]):
RangeError (index): Invalid value: Not in inclusive range 0..18: 19
```
![Capturea](https://user-images.githubusercontent.com/123187910/213874057-f1b11399-0d0c-4b63-a484-28e0948ea92b.PNG)

**Comment by ferraridamiano** [comment]
> also when i try to add another conversion to the drawer it gives an error even i change the const maxConversionUnits to 20 or more. const maxConversionUnits = 20;

This should not be changed

It's really strange. The integration testing in the CI returns no errors.
Have you done any changes to the code?
What flutter version are you using?
Is the code updated to the latest commit?

**Comment by AbuBakar988** [comment]
> This should not be changed

without changing it gives the same error. there are currently 19 numbers of conversions in drawer, if i want to add another or more conversion in drawer then how should i do it? Because when i try to add it gives the error of invalid range when i tap on drawer.

flutter version is Flutter 3.3.9
and the code is not updated to the latest, you have updated some of the codes after i downloaded the source from github.

**Comment by ferraridamiano** [comment]
So you are getting errors on modified code? You did not mention this before!
I can help you only by knowing what are you trying to achieve and what you have done so far
